name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Install Python deps
        run: pip install flet==0.23.*
      - name: Build APK
        run: flet build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
